version: '3.7'

services:

  identity.api:
    image: eshop/identity.api:${TAG:-latest}
    build:
      context: ./src/Services/Identity/Identity.API
      dockerfile: Dockerfile    

  basket.api:
    image: cdis-capacitacion/basket.api
    build:
      context: ./src/Services/Basket/Basket.API
      dockerfile: Dockerfile    

  catalog.api:
    image: cdis-capacitacion/catalog.api
    build:
      context: ./src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile 
    restart: on-failure   

  webshoppingapigw:
    image: eshop/ocelotapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile

  webshoppingagg:
    image: eshop/webshoppingagg:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile

  ordering.api:
    image: cdis-capacitacion/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  payment.api:
    image: cdis-capacitacion/payment.api
    build:
      context: ./src/Services/Payment/Payment.API
      dockerfile: Dockerfile   