version: '3.7'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=CapacitacionMicroservicios.IdentityDb;User Id=sa;Password=Pass@word
      - LocationApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5109
      - MarketingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110
      - BasketApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - MobileShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121
    ports:
      - "5105:80"   

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Initial Catalog=CapacitacionMicroservicios.CatalogDb;User Id=sa;Password=Pass@word
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest        
      - UseCustomizationData=True
    ports:
      - "5101:80"

  basket.api:
    #build:
    #  dockerfile: Dockerfile-debug
    #  target: debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SqlConnectionString=Server=sql.data;Database=CapacitacionMicroservicios.BasketDb;User Id=sa;Password=Pass@word
      - ConnectionString=basket.data
      - identityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
    ports:
      - "5103:80"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Initial Catalog=CapacitacionMicroservicios.OrderingDb;User Id=sa;Password=Pass@word
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest  
      - EVENTSTORE_URL=tcp://admin:changeit@eventstore:1113
    ports:
      - "5104:80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket.api
      - urls__catalog=http://catalog.api
      - urls__orders=http://ordering.api
      - urls__identity=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
    ports:
      - "5121:80"   # Important: In a production environment your should remove the external port (5121) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).
  
  webshoppingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
    ports:
      - "5202:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Shopping/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}